### ISSUE TITLE
Unable to locate or train model "pythia-410m-multicell_v2_2024-07-28_13-55-51_checkpoint-7600_cell_type_pred"

### ISSUE THREAD

**Issue by ayyucedemirbas** [vandijklab/cell2sentence#5]
Hello,

I'm unable to locate the model "pythia-410m-multicell_v2_2024-07-28_13-55-51_checkpoint-7600_cell_type_pred" mentioned in the tutorial. Could you please clarify where I can find this model or provide steps on how to train it?

Thank you so much for your time and attention.

**Comment by SyedA5688** [comment]
Hi there,

The Pythia-410M cell type prediction model can be found on Huggingface under the Files tab, it is the same model checkpoint loaded in the tutorial:
https://huggingface.co/vandijklab/C2S-Pythia-410m-cell-type-prediction

You can either download the model checkpoint files from Huggingface into a folder locally and change the model path in your notebook to your local directory, or alternatively you should also be able to load 'vandijklab/C2S-Pythia-410m-cell-type-prediction' directly since the model is registered on Huggingface (it will automatically be downloaded into a local cache folder in that case). Hope this helps! Let me know if you have any further confusion.

**Comment by ayyucedemirbas** [comment]
Thank you so much!

**Comment by gtg269c** [comment]
Hi, I am having identical issues using the tutorial since it is unable to find the pretrained model in the path. It would be valuable if you can provide example code to load the model weights from huggingface. 

   Thanks

**Comment by SyedA5688** [comment]
Sure thing, for loading the cell type prediction model mentioned in the comment from before, the following is minimal code to load the model:
```
import cell2sentence as cs

save_dir = "/any/existing/path/on/your/device"
save_name = "test_C2S_model_loading"
csmodel = cs.CSModel(
    model_name_or_path="vandijklab/C2S-Pythia-410m-cell-type-prediction",
    save_dir=save_dir,
    save_name=save_name
)  # Loads model using AutoModelForCausalLM.from_pretrained()
print(csmodel)
```

This model is the same as the checkpoint 7600 cell type prediction model, we just renamed the model on Huggingface for convenience. This code should run fine as is (provided you enter in a valid path on your device), since the code will download the model weights automatically from Huggingface (https://huggingface.co/vandijklab/C2S-Pythia-410m-cell-type-prediction). This should also work with any other model we posted on Huggingface, let me know if you have any issues with this.
